language: ruby
rvm:
- 2.5
- 2.6
sudo: false
script:
- bundle exec rspec
notifications:
  slack:
    secure: YHtSwtNqOPj9a96CSNOhDu2eVK+DuqSc5dmQYn0PKnvl3rxtFV+cbRntk3ypaVDm23QEm8K2tHkQE4trjR53FGvMI/wW4YRtJrgf8THz4dy6/LmYPNhW4Mz2IUMfab0MzS+gncbMNsIkufAzOaA7RGGkXoO0Zf6eB/cRKsF4cDY=
